import "../../(app)/globals.css";
import Sidebar from "@/components/layout/sidebar/parent-sidebar";

import { Geist, Geist_Mono } from "next/font/google";
import { baloo2, roboto, amaticSC } from '@/app/(app)/fonts/fonts';
import { AdminSidebar } from "@/components/layout/sidebar/admin-sidebar";
import { AppProvider } from "@/components/appProvider/appProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {

    return (
        <html lang="en">
            <body
                className={`${baloo2.variable} ${roboto.variable} antialiased`}
            >
                <AppProvider>
                    <div className="flex w-full">
                        <AdminSidebar />
                        {children}
                    </div>
                    <ToastContainer
                        position="top-right"
                        autoClose={2000}
                        hideProgressBar={false}
                        newestOnTop
                        closeOnClick
                        pauseOnHover
                        draggable
                    />
                </AppProvider>
            </body>
        </html>
    );
}
